/* Customer-specific adaptations of the SpagoTec-v3 GSAP/ScrollTrigger/Lenis motion basis.
   One trigger per visible, intentional scene; inspect at phone and desktop. */
(()=>{if(!window.gsap||!window.ScrollTrigger)return;gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce)return;const qs=(s)=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];let lenis;if(window.Lenis){lenis=new Lenis({duration:1.05,smoothWheel:true});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0);window.__scheelLenis=lenis}const entries=[];function scrub(el,vars,trigger=el){if(!el||!trigger)return;entries.push({el,trigger,kind:'scrub'});gsap.to(el,{...vars,ease:'none',scrollTrigger:{trigger,start:'top bottom',end:'bottom top',scrub:true}})}function enter(el,from,at='top 86%'){if(!el)return;entries.push({el,trigger:el,kind:'enter'});gsap.from(el,{...from,opacity:1,duration:1.05,ease:'power3.out',immediateRender:false,scrollTrigger:{trigger:el,start:at,once:true}})}function shadow(el){if(!el)return;entries.push({el,trigger:el,kind:'shadow'});gsap.fromTo(el,{filter:'brightness(.76)'},{filter:'brightness(1)',scrollTrigger:{trigger:el,start:'top 90%',end:'top 36%',scrub:true}})}
// Text and text-bearing containers keep full opacity at every scroll position; motion uses transforms only.
// Hero: covered media zooms into the crop, never contracts or reveals bare ground.
const hero=qs('.hero'),vid=qs('#hero-video');if(hero&&vid){entries.push({el:vid,trigger:hero,kind:'hero-zoom'});gsap.fromTo(vid,{scale:1.06},{scale:1.38,ease:'none',scrollTrigger:{trigger:hero,start:'top top',end:'bottom top',scrub:true}})}
enter(qs('.hero-kicker'),{opacity:0,y:35});enter(qs('.hero h1'),{opacity:0,y:60,scale:.97});enter(qs('.hero-sub'),{opacity:0,y:40});enter(qs('.hero-copy .button'),{opacity:0,y:32});scrub(qs('.hero-grid'),{xPercent:-5},hero);scrub(qs('.hero-copy'),{yPercent:-14},hero);
// Intro: section text and rule, distinct media entrances, and a light response to travel.
enter(qs('.intro .section-head'),{opacity:0,y:30});enter(qs('.intro h2'),{opacity:0,y:70});/* Intro copy uses separate scroll-scrubbed ink fill; never fade it to white. */scrub(qs('.intro .section-head'),{xPercent:4});
all('.service').forEach((card,i)=>{const photo=card.querySelector('.service-photo'),info=card.querySelector('.service-info'),title=info.querySelector('h3'),body=info.querySelector('p'),eyebrow=card.querySelector('.caption'),foot=info.querySelector('span');enter(photo,{opacity:0,y:65,clipPath:'inset(16% 0% 0% 0%)'});shadow(photo);scrub(photo,{backgroundPositionY:(i===2?55:70)+'%'});enter(eyebrow,{opacity:0,y:18});enter(title,{opacity:0,y:42});enter(body,{opacity:0,y:28});enter(foot,{opacity:0,x:-20});});
// Concept: independently moving planes indicate a joint system, not a fake product shot.
enter(qs('.statement-copy .tag'),{opacity:0,x:25});enter(qs('.statement-copy h2'),{opacity:0,x:65});enter(qs('.statement-copy p'),{opacity:0,x:38});enter(qs('.statement-copy .button'),{opacity:0,y:25});all('.statement-art span').forEach((pane,i)=>{enter(pane,{opacity:0,rotateY:-32,y:80});scrub(pane,{yPercent:[-14,8,16][i]});});
// Process and lead handoff: headline, each step, form and controls have separate timing.
enter(qs('.steps .section-head'),{opacity:0,y:25});enter(qs('.steps h2'),{opacity:0,y:55});all('.step').forEach(row=>{enter(row.querySelector('b'),{opacity:0,x:-28});enter(row.querySelector('h3'),{opacity:0,y:35});enter(row.querySelector('p'),{opacity:0,x:35})});
enter(qs('.contact-left .tag'),{opacity:0,y:24});enter(qs('.contact h2'),{opacity:0,y:65});enter(qs('.contact-left p'),{opacity:0,y:36});enter(qs('.form-card'),{opacity:0,y:70,rotateX:4});all('.form-card fieldset').forEach(f=>enter(f,{opacity:0,y:25}));enter(qs('.form-card .button'),{opacity:0,y:22});enter(qs('.footer-top'),{opacity:0,y:30});enter(qs('.footer-bottom'),{opacity:0,y:20});
const mark=document.createElement('div');mark.className='progress-line';mark.setAttribute('aria-hidden','true');document.body.append(mark);entries.push({el:mark,trigger:document.documentElement,kind:'progress'});ScrollTrigger.create({start:0,end:'max',onUpdate:self=>mark.style.transform=`scaleX(${self.progress})`});window.__scheelMotionEntries=entries;window.__scheelMotionCount=()=>ScrollTrigger.getAll().length;setTimeout(()=>ScrollTrigger.refresh(),500);
})();
